
project_id = "gyyhnbzekafnvxflhlni"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://platform.cloudnotes.click"
additional_redirect_urls = ["https://platform.cloudnotes.click/auth/confirm"]
# email_template_forgot_password_life_time_seconds = 86400
# email_template_magic_link_life_time_seconds = 86400
# email_template_verification_life_time_seconds = 86400

[analytics]
enabled = false

[functions.send-email]
verify_jwt = true

[functions.newsletter-subscribe]
enabled = true
verify_jwt = false
import_map = "supabase/functions/newsletter-subscribe/deno.json"
entrypoint = "supabase/functions/newsletter-subscribe/index.ts"

[functions.newsletter-unsubscribe]
enabled = true
verify_jwt = true
import_map = "supabase/functions/newsletter-unsubscribe/deno.json"
entrypoint = "supabase/functions/newsletter-unsubscribe/index.ts"

[functions.create-newuser-folder]
enabled = true
verify_jwt = true
import_map = "./functions/create-newuser-folder/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-newuser-folder/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-newuser-folder/*.html" ]
