
project_id = "gyyhnbzekafnvxflhlni"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://platform.cloudnotes.click"

[analytics]
enabled = false

[functions.send-email]
verify_jwt = true

[functions.newsletter-subscribe]
enabled = true
verify_jwt = true
import_map = "./functions/newsletter-subscribe/deno.json"
entrypoint = "./functions/newsletter-subscribe/index.ts"

[functions.newsletter-unsubscribe]
enabled = true
verify_jwt = true
import_map = "./functions/newsletter-unsubscribe/deno.json"
entrypoint = "./functions/newsletter-unsubscribe/index.ts"
